package ru.kaelesty.madprojects.ui.strings

object StringResources {
    const val GreetingTitle = "Привет!\nС чего начнём?"

    const val AppName = "madprojects"
    const val LoginTitle = "Вход"
    const val EmailLabel = "Email"
    const val PasswordLabel = "Пароль"
    const val EmailPlaceholder = "cheeseonthemoon@email.com"
    const val PasswordPlaceholder = "Введите пароль"
    const val LoginButton = "Вход"
    const val RegisterButton = "Регистрация"
    const val BackButton = "Назад"
    const val ContinueButton = "Продолжить"
    const val ErrorEmptyEmail = "Введите e-mail"
    const val ErrorEmptyPassword = "Введите пароль"
    const val ErrorInvalidEmail = "Некорректный e-mail"
    const val ErrorInvalidPasswordPolicy = "Пароль от 10 символов, с цифрой, строчной и прописной буквой и спецсимволом"
    const val ErrorLogin = "Неверный e-mail или пароль"
    const val ErrorUnavailable = "Сервис временно недоступен"

    const val HeaderLogo = "mp"
    const val ProfileTitle = "Профиль"
    const val ProfilePlaceholder = "Профиль"
    const val CuratorProfilePlaceholder = "Профиль куратора"
    const val ProfileAvatar = "Аватар профиля"
    const val ProfileEmailLabel = "Email: "
    const val ProfileGroupLabel = "Группа: "
    const val ProfileProjectsTitle = "Проекты"
    const val ProfileProjectsEmpty = "Проектов пока нет"
    const val ProfileProjectsMenu = "Меню проектов"
    const val ProfileProjectsCreate = "Создать проект"
    const val ProfileProjectsJoin = "Присоединиться к проекту"
    const val LoadError = "Ошибка загрузки"
    const val RetryButton = "Попробовать снова"
    const val ProjectStatusPending = "На проверке"
    const val ProjectStatusApproved = "Одобрен"
    const val ProjectStatusUnapproved = "Отклонен"
}

